// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALjsRz8Q_VQasjctZRQR4UeElFNetYOSg',
    appId: '1:920154671018:web:416dcd315bd3deef060dd3',
    messagingSenderId: '920154671018',
    projectId: 'demoproject-2f51c',
    authDomain: 'demoproject-2f51c.firebaseapp.com',
    storageBucket: 'demoproject-2f51c.appspot.com',
    measurementId: 'G-WNG22H1D02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApFtfzPfVZpbwgzTrlgmECXn1zV9Ojmew',
    appId: '1:920154671018:android:a784d4e6fd75000a060dd3',
    messagingSenderId: '920154671018',
    projectId: 'demoproject-2f51c',
    storageBucket: 'demoproject-2f51c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoagDxFrnQfO5r5OI8NZc2SMpJHN3UvKQ',
    appId: '1:920154671018:ios:3caf85b6c399c1b8060dd3',
    messagingSenderId: '920154671018',
    projectId: 'demoproject-2f51c',
    storageBucket: 'demoproject-2f51c.appspot.com',
    androidClientId: '920154671018-cn77qdb5uq39r6vd60fu5a8ep4koh8p9.apps.googleusercontent.com',
    iosClientId: '920154671018-rnfig7hlnbd0l37k4c1qljofv04q3m0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattybuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoagDxFrnQfO5r5OI8NZc2SMpJHN3UvKQ',
    appId: '1:920154671018:ios:3caf85b6c399c1b8060dd3',
    messagingSenderId: '920154671018',
    projectId: 'demoproject-2f51c',
    storageBucket: 'demoproject-2f51c.appspot.com',
    androidClientId: '920154671018-cn77qdb5uq39r6vd60fu5a8ep4koh8p9.apps.googleusercontent.com',
    iosClientId: '920154671018-rnfig7hlnbd0l37k4c1qljofv04q3m0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattybuzz',
  );
}
